### ISSUE TITLE
Can we supplement our ATAC models with DHS?

### ISSUE THREAD

**Issue by tacazares** [MiraldiLab/maxATAC#10]
We want to test whether we can use DHS data to supplement our ATAC-seq data in our models. 

We will use our 11 core TFs. We will split the ATAC-seq 50/50 with DHS data. We will also test a model of DHS only. 

***Tasks***
- [x] Download all BAM for ENCODE data of interest
- [x] Filter for quality
- [x] Normalize DHS signal tracks
- [x] Average signal tracks
- [x] Min-max normalize
- [x] Generate run meta files (use slop20 peaks)
- [x] Generate ROI
- [x] Train model
- [x] Select best models
- [x] Predict
- [x] Benchmark and Analyze

Updated task list based on https://github.com/MiraldiLab/maxATAC/issues/10#issuecomment-789143042

 - [x] Identifying the TFs with 4 cell types available
 - [x] Assess the quality of models trained with 2 of the 4 cell types available.
 - [x] Add an additional cell type for a total of 2 ATAC + 1 DHS and assess AUPR
 - [x] Repeat the above step for the 4th sample.
